spring:
  application:
    name: eureka-service
server:
  port: 8761
  address: 0.0.0.0
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URL:http://gpadmin:1234@localhost:8761/eureka} # Jenkins 환경변수 EUREKA_URL이 있으면 사용, 없으면 localhost
  server:
    peer-node-read-timeout-ms: 60000
    peer-node-connect-timeout-ms: 60000