spring:
  application:
    name: eureka-service

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://gpadmin:1234@localhost:8761/eureka/
  server:
    peer-node-read-timeout-ms: 60000
    peer-node-connect-timeout-ms: 60000