apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
  namespace: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
        - name: eureka-service
          image: roin09/eureka-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          envFrom:
            - configMapRef:
                name: eureka-config
